[package]
name = "locale"
description = "A small api to get the primary and backup locales of a user"
version = "0.1.0"
authors = ["Mike Engel <mike@mike-engel.com>"]

[dependencies]
rocket = "0.2"
rocket_codegen = "0.2"
rocket_contrib = "0.2"
futures = "0.1"
accept-language = "1.0"
serde_json = "1"
serde_derive = "1"
