[package]
name = "locale"
description = "A polyfill to understand your users' preferred languages"
version = "1.0.1"
authors = ["Mike Engel <mike@mike-engel.com>"]

[dependencies]
rocket = "0.2.7"
rocket_codegen = "0.2.7"
futures = "0.1"
accept-language = "1.0"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"

[dependencies.rocket_contrib]
version = "0.2.7"
features = ["handlebars_templates"]
